using System.ComponentModel.DataAnnotations;
namespace MallEnergyBilling.Web.Models;
public enum ShopStatus{Active,Vacant,Inactive} public enum ReadingSource{Automatic,Manual,Simulated,Imported} public enum PowerSource{Grid,Generator} public enum BillingStatus{Open,ReadingsCaptured,Calculated,Finalized,Closed} public enum InvoiceStatus{Draft,Finalized,PartiallyPaid,Paid,Overdue,Cancelled} public enum RegisterDataType{UInt16,Int16,UInt32,Int32,Float32,UInt64} public enum WordOrder{HighLow,LowHigh}
public sealed class Controller{public int Id{get;set;}[Required]public string Name{get;set;}="";public string MdbPanel{get;set;}="";public string CommunicationType{get;set;}="ModbusRtu";public string ComPort{get;set;}="COM1";public int BaudRate{get;set;}=9600;public string Parity{get;set;}="Even";public int DataBits{get;set;}=8;public int StopBits{get;set;}=1;public byte SlaveAddress{get;set;}=1;public int PollingIntervalSeconds{get;set;}=5;public int TimeoutMilliseconds{get;set;}=1000;public int RetryCount{get;set;}=2;public bool Enabled{get;set;}=true;public DateTimeOffset? LastSuccess{get;set;}public string Condition{get;set;}="Ready to configure";public string Notes{get;set;}="";}
public sealed class Shop{public int Id{get;set;}[Required]public string ShopNumber{get;set;}="";[Required]public string Name{get;set;}="";public string TenantName{get;set;}="";public string ContactPerson{get;set;}="";public string Telephone{get;set;}="";[EmailAddress]public string Email{get;set;}="";public string Floor{get;set;}="";public string Zone{get;set;}="";public string MdbPanel{get;set;}="";public ShopStatus Status{get;set;}=ShopStatus.Active;public string BillingAddress{get;set;}="";public string TaxNumber{get;set;}="";public string Notes{get;set;}="";}
public sealed class Meter{public int Id{get;set;}[Required]public string Name{get;set;}="";[Required]public string SerialNumber{get;set;}="";public string Model{get;set;}="";public int ShopId{get;set;}public Shop? Shop{get;set;}public int ControllerId{get;set;}public Controller? Controller{get;set;}public PowerSource PowerSource{get;set;}=PowerSource.Grid;public int StartingRegister{get;set;}public RegisterDataType DataType{get;set;}=RegisterDataType.UInt32;public WordOrder WordOrder{get;set;}=WordOrder.HighLow;public decimal ScalingFactor{get;set;}=.01m;public int PulseConstant{get;set;}=1600;public decimal CtPrimary{get;set;}=1;public decimal CtSecondary{get;set;}=1;public bool CtAppliedByPlc{get;set;}=true;public decimal InitialReading{get;set;}public DateOnly CommissioningDate{get;set;}=DateOnly.FromDateTime(DateTime.Today);public bool Active{get;set;}=true;public decimal LastReading{get;set;}public DateTimeOffset? LastReadingAt{get;set;}public string CommunicationStatus{get;set;}="Not commissioned";public decimal SimulatedLoadKw{get;set;}public bool SimulationRunning{get;set;}public bool SimulateFailure{get;set;}public bool SimulateFrozen{get;set;}public string Notes{get;set;}="";}
public sealed class MeterReading{public long Id{get;set;}public int MeterId{get;set;}public Meter? Meter{get;set;}public ulong RawValue{get;set;}public decimal AccumulatedKwh{get;set;}public DateTimeOffset Timestamp{get;set;}public ReadingSource Source{get;set;}public string Quality{get;set;}="Good";public string? UserId{get;set;}public string Reason{get;set;}="";public bool UsedForBilling{get;set;}public bool RequiresReview{get;set;}}
public sealed class Tariff{public int Id{get;set;}public int? MeterId{get;set;}public Meter? Meter{get;set;}public decimal PricePerKwh{get;set;}public string Currency{get;set;}="USD";public DateTimeOffset EffectiveFrom{get;set;}public DateTimeOffset CreatedAt{get;set;}public string ChangedBy{get;set;}="System";public string Reason{get;set;}="";}
public sealed class BillingPeriod{public int Id{get;set;}public string Number{get;set;}="";public DateOnly StartDate{get;set;}public DateOnly EndDate{get;set;}public BillingStatus Status{get;set;}public DateTimeOffset CreatedAt{get;set;}public DateTimeOffset? FinalizedAt{get;set;}public string ResponsibleUser{get;set;}="";}
public sealed class InvoiceSchedule{public int Id{get;set;}public int PublicationDay{get;set;}=1;public DateTimeOffset GenerateAt{get;set;}public int DueDays{get;set;}=10;public bool Completed{get;set;}public DateTimeOffset CreatedAt{get;set;}public DateTimeOffset? CompletedAt{get;set;}public string CreatedBy{get;set;}="";public string? Result{get;set;}}
public sealed class Invoice{public int Id{get;set;}public string InvoiceNumber{get;set;}="";public int BillingPeriodId{get;set;}public BillingPeriod? BillingPeriod{get;set;}public int MeterId{get;set;}public Meter? Meter{get;set;}public int ShopId{get;set;}public Shop? Shop{get;set;}public DateTimeOffset InvoiceDate{get;set;}public DateTimeOffset DueDate{get;set;}public decimal OpeningReading{get;set;}public decimal ClosingReading{get;set;}public decimal ConsumptionKwh{get;set;}public decimal TariffPerKwh{get;set;}public decimal EnergyCharge{get;set;}public decimal FixedCharges{get;set;}public decimal OtherCharges{get;set;}public decimal Tax{get;set;}public decimal Discount{get;set;}public decimal PreviousBalance{get;set;}public decimal Total{get;set;}public string Currency{get;set;}="USD";public InvoiceStatus Status{get;set;}public bool Locked{get;set;}public string SnapshotJson{get;set;}="";public string Notes{get;set;}="";public List<Payment> Payments{get;set;}=[];public decimal PaidAmount=>Payments.Sum(x=>x.Amount);public decimal Balance=>Total-PaidAmount;}
public sealed class Payment{public int Id{get;set;}public int InvoiceId{get;set;}public Invoice? Invoice{get;set;}public DateTimeOffset PaymentDate{get;set;}public decimal Amount{get;set;}public string Currency{get;set;}="USD";public string Method{get;set;}="Cash";public string ReferenceNumber{get;set;}="";public string ReceivedBy{get;set;}="";public string Notes{get;set;}="";}
public sealed class AuditLog{public long Id{get;set;}public DateTimeOffset Timestamp{get;set;}public string UserId{get;set;}="System";public string Action{get;set;}="";public string EntityType{get;set;}="";public string EntityId{get;set;}="";public string OldValue{get;set;}="";public string NewValue{get;set;}="";public string Reason{get;set;}="";public string SourceIp{get;set;}="";}
