using Controller=MallEnergyBilling.Web.Models.Controller;using MallEnergyBilling.Web.Data;using MallEnergyBilling.Web.Models;using MallEnergyBilling.Web.Services;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.Data.Sqlite;using Microsoft.EntityFrameworkCore;namespace MallEnergyBilling.Web.Pages.Operations;
public class IndexModel(ApplicationDbContext db,AppDataPaths paths,DatabaseMaintenanceService maintenance):PageModel
{
 public List<Controller>Controllers{get;set;}=[];public List<Shop>Shops{get;set;}=[];public List<Meter>Meters{get;set;}=[];public List<Tariff>Tariffs{get;set;}=[];public List<MeterReading>Readings{get;set;}=[];
 public string BackupPath=>paths.BackupDirectory;public List<BackupFile>BackupFiles{get;set;}=[];public sealed record BackupFile(string Name,long Size,DateTime Modified);
 public IReadOnlyList<string>Currencies{get;}=["UGX","USD","EUR","GBP","AED","AFN","ALL","AMD","ANG","AOA","ARS","AUD","AWG","AZN","BAM","BBD","BDT","BGN","BHD","BIF","BMD","BND","BOB","BRL","BSD","BTN","BWP","BYN","BZD","CAD","CDF","CHF","CLP","CNY","COP","CRC","CUP","CVE","CZK","DJF","DKK","DOP","DZD","EGP","ERN","ETB","FJD","FKP","GEL","GHS","GIP","GMD","GNF","GTQ","GYD","HKD","HNL","HTG","HUF","IDR","ILS","INR","IQD","IRR","ISK","JMD","JOD","JPY","KES","KGS","KHR","KMF","KPW","KRW","KWD","KYD","KZT","LAK","LBP","LKR","LRD","LSL","LYD","MAD","MDL","MGA","MKD","MMK","MNT","MOP","MRU","MUR","MVR","MWK","MXN","MYR","MZN","NAD","NGN","NIO","NOK","NPR","NZD","OMR","PAB","PEN","PGK","PHP","PKR","PLN","PYG","QAR","RON","RSD","RUB","RWF","SAR","SBD","SCR","SDG","SEK","SGD","SHP","SLE","SOS","SRD","SSP","STN","SVC","SYP","SZL","THB","TJS","TMT","TND","TOP","TRY","TTD","TWD","TZS","UAH","UYU","UZS","VES","VND","VUV","WST","XAF","XCD","XOF","XPF","YER","ZAR","ZMW","ZWL"];
 public async Task OnGet(){Controllers=await db.Controllers.ToListAsync();Shops=await db.Shops.ToListAsync();Meters=await db.Meters.Include(x=>x.Shop).ToListAsync();Tariffs=await db.Tariffs.Include(x=>x.Meter).OrderByDescending(x=>x.Id).ToListAsync();Readings=await db.MeterReadings.Include(x=>x.Meter).OrderByDescending(x=>x.Id).Take(100).ToListAsync();LoadBackups();}
 public async Task<IActionResult>OnPostTariff(int meterId,decimal price,string currency,DateTime effective,string reason){if(price<=0)return BadRequest("A positive price is required.");currency=(currency??"").Trim().ToUpperInvariant();if(currency.Length!=3||currency.Any(c=>c<'A'||c>'Z'))return BadRequest("Select a valid three-letter ISO currency code.");var meter=await db.Meters.FindAsync(meterId);if(meter is null)return BadRequest("Select a valid meter.");var auditReason=string.IsNullOrWhiteSpace(reason)?"Not provided":reason.Trim();var old=await db.Tariffs.Where(x=>x.MeterId==meterId).OrderByDescending(x=>x.Id).FirstOrDefaultAsync();var t=new Tariff{MeterId=meterId,PricePerKwh=price,Currency=currency,EffectiveFrom=effective,CreatedAt=DateTimeOffset.UtcNow,ChangedBy=User.Identity?.Name??"Local administrator",Reason=auditReason};db.Tariffs.Add(t);db.AuditLogs.Add(new(){Timestamp=DateTimeOffset.UtcNow,UserId=t.ChangedBy,Action="Meter tariff changed",EntityType="Meter",EntityId=meterId.ToString(),OldValue=old is null?"none":$"{old.Currency} {old.PricePerKwh}",NewValue=$"{currency} {price}",Reason=auditReason,SourceIp=HttpContext.Connection.RemoteIpAddress?.ToString()??""});await db.SaveChangesAsync();return RedirectToPage(null,null,"tariffs");}
 public async Task<FileResult>OnGetCsv(){var rows=await db.MeterReadings.Include(x=>x.Meter).OrderBy(x=>x.Id).ToListAsync();var text="Timestamp,Meter,Raw,AccumulatedKwh,Source,Quality\r\n"+string.Join("\r\n",rows.Select(x=>$"{x.Timestamp:O},{x.Meter?.Name},{x.RawValue},{x.AccumulatedKwh},{x.Source},{x.Quality}"));return File(System.Text.Encoding.UTF8.GetBytes(text),"text/csv","meter-readings.csv");}
 public async Task<IActionResult>OnPostBackup(){if(!User.IsInRole("Administrator"))return Forbid();Directory.CreateDirectory(BackupPath);var sourcePath=paths.DatabasePath;var destinationPath=Path.Combine(BackupPath,$"watch-dog-em-{DateTime.Now:yyyyMMdd-HHmmss}.db");await maintenance.Gate.WaitAsync(HttpContext.RequestAborted);try{await db.Database.CloseConnectionAsync();await using var source=new SqliteConnection($"Data Source={sourcePath};Mode=ReadOnly");await using var destination=new SqliteConnection($"Data Source={destinationPath}");await source.OpenAsync();await destination.OpenAsync();source.BackupDatabase(destination);TempData["BackupSuccess"]=$"Backup created: {Path.GetFileName(destinationPath)}";}finally{maintenance.Gate.Release();}return RedirectToPage(null,null,"backup");}
 public async Task<IActionResult>OnPostRestore(string fileName){if(!User.IsInRole("Administrator"))return Forbid();if(string.IsNullOrWhiteSpace(fileName)||Path.GetFileName(fileName)!=fileName){TempData["BackupError"]="Invalid backup file.";return RedirectToPage(null,null,"backup");}var backupPath=Path.Combine(BackupPath,fileName);if(!System.IO.File.Exists(backupPath)){TempData["BackupError"]="Backup file was not found.";return RedirectToPage(null,null,"backup");}await maintenance.Gate.WaitAsync(HttpContext.RequestAborted);try{await db.Database.CloseConnectionAsync();SqliteConnection.ClearAllPools();await using var source=new SqliteConnection($"Data Source={backupPath};Mode=ReadOnly");await source.OpenAsync();await using(var check=source.CreateCommand()){check.CommandText="PRAGMA quick_check;";if(!string.Equals((string?)await check.ExecuteScalarAsync(),"ok",StringComparison.OrdinalIgnoreCase)){TempData["BackupError"]="The selected backup failed its integrity check.";return RedirectToPage(null,null,"backup");}}await using var destination=new SqliteConnection($"Data Source={paths.DatabasePath}");await destination.OpenAsync();source.BackupDatabase(destination);SqliteConnection.ClearAllPools();TempData["BackupSuccess"]=$"Restored {fileName}.";}finally{maintenance.Gate.Release();}return RedirectToPage(null,null,"backup");}
 void LoadBackups(){Directory.CreateDirectory(BackupPath);BackupFiles=new DirectoryInfo(BackupPath).GetFiles("*.db").OrderByDescending(x=>x.LastWriteTimeUtc).Select(x=>new BackupFile(x.Name,x.Length,x.LastWriteTime)).ToList();}
}
