using System.ComponentModel.DataAnnotations;using System.Text.Json;using MallEnergyBilling.Web.Data;using MallEnergyBilling.Web.Models;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.EntityFrameworkCore;
namespace MallEnergyBilling.Web.Pages.Admin.Controllers;
public sealed class MeterModel(ApplicationDbContext db):PageModel
{
 [BindProperty]public InputModel Input{get;set;}=new(); public List<Shop>Shops{get;private set;}=[];public string ControllerName{get;private set;}="";
 public sealed class InputModel{public int Id{get;set;}[Required]public string Name{get;set;}="";[Required]public string SerialNumber{get;set;}="";[Range(1,int.MaxValue)]public int ShopId{get;set;}public bool Active{get;set;}[Range(0,65535)]public int StartingRegister{get;set;}public RegisterDataType DataType{get;set;}public WordOrder WordOrder{get;set;}[Range(typeof(decimal),"0.00000001","1000000")]public decimal ScalingFactor{get;set;}[Range(1,1000000)]public int PulseConstant{get;set;}[Range(typeof(decimal),"0.0001","1000000")]public decimal CtPrimary{get;set;}[Range(typeof(decimal),"0.0001","1000000")]public decimal CtSecondary{get;set;}public bool CtAppliedByPlc{get;set;}public string Notes{get;set;}="";public string Reason{get;set;}="";}
 public async Task<IActionResult>OnGetAsync(int id){await LoadShops();var m=await db.Meters.Include(x=>x.Controller).FirstOrDefaultAsync(x=>x.Id==id);if(m is null)return NotFound();ControllerName=m.Controller?.Name??"";Input=new(){Id=m.Id,Name=m.Name,SerialNumber=m.SerialNumber,ShopId=m.ShopId,Active=m.Active,StartingRegister=m.StartingRegister,DataType=m.DataType,WordOrder=m.WordOrder,ScalingFactor=m.ScalingFactor,PulseConstant=m.PulseConstant,CtPrimary=m.CtPrimary,CtSecondary=m.CtSecondary,CtAppliedByPlc=m.CtAppliedByPlc,Notes=m.Notes};return Page();}
 public async Task<IActionResult>OnPostAsync(){await LoadShops();var m=await db.Meters.Include(x=>x.Controller).FirstOrDefaultAsync(x=>x.Id==Input.Id);if(m is null)return NotFound();ControllerName=m.Controller?.Name??"";if(!ModelState.IsValid)return Page();if(await db.Meters.AnyAsync(x=>x.Id!=m.Id&&x.SerialNumber==Input.SerialNumber)){ModelState.AddModelError("Input.SerialNumber","Meter serial number must be unique.");return Page();}if(await db.Meters.AnyAsync(x=>x.Id!=m.Id&&x.ControllerId==m.ControllerId&&x.StartingRegister==Input.StartingRegister)){ModelState.AddModelError("Input.StartingRegister","This register is already assigned on the controller.");return Page();}var old=JsonSerializer.Serialize(m);m.Name=Input.Name.Trim();m.SerialNumber=Input.SerialNumber.Trim();m.ShopId=Input.ShopId;m.Active=Input.Active;m.StartingRegister=Input.StartingRegister;m.DataType=Input.DataType;m.WordOrder=Input.WordOrder;m.ScalingFactor=Input.ScalingFactor;m.PulseConstant=Input.PulseConstant;m.CtPrimary=Input.CtPrimary;m.CtSecondary=Input.CtSecondary;m.CtAppliedByPlc=Input.CtAppliedByPlc;m.Notes=Input.Notes?.Trim()??"";m.CommunicationStatus=m.Active?"Awaiting poll":"Not commissioned";db.AuditLogs.Add(new(){Timestamp=DateTimeOffset.UtcNow,UserId=User.Identity?.Name??"Administrator",Action="Meter channel configuration changed",EntityType="Meter",EntityId=m.Id.ToString(),OldValue=old,NewValue=JsonSerializer.Serialize(Input),Reason=string.IsNullOrWhiteSpace(Input.Reason)?"Not provided":Input.Reason.Trim(),SourceIp=HttpContext.Connection.RemoteIpAddress?.ToString()??""});await db.SaveChangesAsync();return RedirectToPage("Channels",new{id=m.ControllerId});}
 async Task LoadShops()=>Shops=await db.Shops.OrderBy(x=>x.ShopNumber).ToListAsync();
}
