<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MallEnergyBilling.Web-b9f01abe-f1c0-4aab-8ecc-68e4eb3a1a43</UserSecretsId>
    <ApplicationIcon>..\..\Watch Dog.ico</ApplicationIcon>
    <Version>1.8.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Deployment\Start Mall Energy.cmd" Link="Start Mall Energy.cmd" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.30" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>
